# Generated by Django 4.2.5 on 2023-09-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_hashtag_alter_ads_options_ads_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_app.category'),
        ),
        migrations.CreateModel(
            name='AdsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads')),
                ('ads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.ads')),
            ],
        ),
    ]
